### ISSUE TITLE
Some suggestions for improvement

### ISSUE THREAD

**Issue by mweststrate** [chicoxyzzy/rx-mobx#1]
(copied from https://github.com/mweststrate/mobservable/issues/57)

Looks nice and straight forward!

Some suggestions for improvement: 
1. I think it is nice to add a second property name parameter to `mobservableToRx`, so that individual object properties can also be observed easily. I just added support for such a second param to `mobservable.observe` as well in 1.1.8 (see #59).
2. In the disposer of `rxToMobservable` the `mobservable()` call is unnecessary I think.
3. what should happen on Rx end / error events? For both it might be interesting to pass special values into the mobservable observable so that observers can see that the backing stream has ended and no new values should be expected. That enables observers to cleanup by no longer using the observable value (which can be GC-ed after that).

**Comment by chicoxyzzy** [comment]
Thank you for your suggestions! I'll take a look next week

**Comment by chicoxyzzy** [comment]
Sorry for delay. It's because of lack of time :( BTW PRs are welcome! Also I'll try to find some time to work on `rx-mobservable` ASAP

**Comment by chicoxyzzy** [comment]
Fixed by #2

I've added you to npm owners of `rx-mobx` package
