### ISSUE TITLE
rxjs peer dependency incorrect

### ISSUE THREAD

**Issue by jmerriweather** [chicoxyzzy/rx-mobx#4]
I get the following error when installing rx-mobx:

> npm WARN rx-mobx@1.1.1 requires a peer of rxjs@^5.0.0-beta.0 but none was installed.

I believe it needs to depend on **rxjs-es** instead of **rxjs**

**Comment by chicoxyzzy** [comment]
Make sure that you have `rxjs` module in your `node_modules`. `rxjs` is a peer dependancy of `rx-mobx`

**Comment by chicoxyzzy** [comment]
Closing this for now because this is likely just a missing `rxjs` dependency in your `package.json`
