### ISSUE TITLE
Help @computed/@observable

### ISSUE THREAD

**Issue by genaby** [chicoxyzzy/rx-mobx#5]
How to convert @computed/@observable  (I mean defined with help of decorators)?

**Comment by chicoxyzzy** [comment]
Personally I don't use decorators or any else proposal which has maturity stage less than 3. To be honest I don't even use mobx for now. Can you provide an example of code? It'll be much easier to help you.

**Comment by mweststrate** [comment]
Note that you can get the underlying observable by using
`mobx.extras.getAtom(object, "propertyName")`. Or just `computed(() =>
object.propertyName)` ;-)

Op di 4 okt. 2016 om 14:28 schreef Sergey Rubanov <notifications@github.com
